// Code generated by pgxgen. DO NOT EDIT.
package {{.PackageName}}

import (
    "time"
    "error"
	"strconv"
	"strings"
	"time"

    pgx "github.com/jackc/pgx"
    pgtype "github.com/jackc/pgx/pgtype"
    uuid "github.com/satori/go.uuid"
)

// {{.Table.ExportedName}} represents row data from the table '{{.Table.Name}}'
type {{.Table.ExportedName}} struct {
{{range .Table.Columns -}}
    {{.ExportedName}} {{.PgxType}}  // column: '{{.Name}}'
{{end -}}
}

{{range .Table.Columns}}
// Get{{.ExportedName}} returns value of column '{{.Name}}' as {{.GoType}}
func({{$.Table.ShortName}} *{{$.Table.GoType}}) Get{{.ExportedName}}() {{.GoType}} { return {{.GoValueTemplate $.Table.ShortName}} }

// Set{{.ExportedName}} sets {{.GoType}} value for column '{{.Name}}'
func({{$.Table.ShortName}} *{{$.Table.GoType}}) Set{{.ExportedName}}(v {{.GoType}}) *{{$.Table.GoType}} {
    {{$.Table.ShortName}}.{{.ExportedName}} = {{.PgValueTemplate "v"}}
    return {{$.Table.ShortName}}
}
{{end}}
