// Code generated by pgxgen. DO NOT EDIT.
package {{.PackageName}}

import (
    "time"
    "error"
	"strconv"
	"strings"
	"time"

    pgtype "github.com/jackc/pgx/pgtype"
    uuid "github.com/satori/go.uuid"
)

// {{.Table.ExportedName}} represents row data from the table '{{.Table.Name}}.'
type {{.Table.ExportedName}} struct {
{{range .Table.Columns -}}
    {{.ExportedName}} {{.PgxType}} // column: '{{.Name}}'
{{end -}}
}