// Code generated by pgxgen. DO NOT EDIT.
package {{.PackageName}}

import (
	"encoding/hex"
	"strconv"

	"github.com/jackc/pgx/pgtype"
	"github.com/satori/go.uuid"
)

func TextToString(v pgtype.Text) string               { return v.String }
func VarcharToString(v pgtype.Text) string            { return v.String }
func ByteaToString(v pgtype.Bytea) string             { return hex.EncodeToString(v.Bytes) }
func Int2ToString(v pgtype.Int2) string               { return strconv.FormatInt(int64(v.Int), 10) }
func Int4ToString(v pgtype.Int4) string               { return strconv.FormatInt(int64(v.Int), 10) }
func Int8ToString(v pgtype.Int8) string               { return strconv.FormatInt(v.Int, 10) }
func Float4ToString(v pgtype.Float4) string           { return strconv.FormatFloat(float64(v.Float), 'f', -1, 32) }
func Float8ToString(v pgtype.Float8) string           { return strconv.FormatFloat(v.Float, 'f', -1, 64) }
func BoolToString(v pgtype.Bool) string               { return strconv.FormatBool(v.Bool) }
func UUIDToString(v pgtype.UUID) string               { return uuid.FromBytesOrNil(v.Bytes[:]).String() }
func TimestampToString(v pgtype.Timestamp) string     { return v.Time.String() }
func TimestamptzToString(v pgtype.Timestamptz) string { return v.Time.String() }

{{range .Data.Enums -}}
func {{.ExportedName}}ToString(v {{$.ModelPackageName}}.{{.ExportedName}}) string {return v.String}
{{end -}}